apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-forecast-api
  template:
    metadata:
      labels:
        app: weather-forecast-api
    spec:
      containers:
      - name: weather-forecast-api
        image: leonardodutra/weather-forecast-api:latest
        ports:
        - containerPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-api
spec:
  selector:
    app: weather-forecast-api
  ports:
    - port: 80           # Porta interna do service
      targetPort: 8095     # Porta em que a API está rodando no container
      nodePort: 30001    # Porta externa
  type: NodePort